.TH SSH-SK-HELPER 8 "December 21 2019 " ""
.SH NAME
\fBssh-sk-helper\fP
\- OpenSSH helper for FIDO authenticator support
.SH SYNOPSIS
.br
\fBssh-sk-helper\fP
[\fB\-v\fP]
.SH DESCRIPTION
\fBssh-sk-helper\fP
is used by
\fBssh-agent\fP(1)
to access keys provided by a FIDO authenticator.

\fBssh-sk-helper\fP
is not intended to be invoked by the user, but from
\fBssh-agent\fP(1).

A single option is supported:
.TP
\fB\-v\fP
Verbose mode.
Causes
\fBssh-sk-helper\fP
to print debugging messages about its progress.
This is helpful in debugging problems.
Multiple
\fB\-v\fP
options increase the verbosity.
The maximum is 3.

Note that
\fBssh-agent\fP(1)
will automatically pass the
\fB\-v\fP
flag to
\fBssh-sk-helper\fP
when it has itself been placed in debug mode.
.PP
.SH SEE ALSO
\fBssh\fP(1),
\fBssh-add\fP(1),
\fBssh-agent\fP(1)
.SH HISTORY
\fBssh-sk-helper\fP
first appeared in
OpenBSD 6.7 .
.SH AUTHORS

Damien Miller <Mt djm@openbsd.org>
